export const DEPARTMENTS = [
	{ value: "AMAZONAS", label: "Amazonas" },
	{ value: "ANTIOQUIA", label: "Antioquia" },
	{ value: "ARAUCA", label: "Arauca" },
	{ value: "ARCHIPIELAGO DE SAN ANDRES PROVIDENCIA Y SANTA CATALINA", label: "San Andrés, Providencia y Santa Catalina" },
	{ value: "ATLANTICO", label: "Atlántico" },
	{ value: "BOLIVAR", label: "Bolívar" },
	{ value: "BOYACA", label: "Boyacá" },
	{ value: "CALDAS", label: "Caldas" },
	{ value: "CAQUETA", label: "Caquetá" },
	{ value: "CASANARE", label: "Casanare" },
	{ value: "CAUCA", label: "Cauca" },
	{ value: "CESAR", label: "Cesar" },
	{ value: "CHOCO", label: "Chocó" },
	{ value: "CORDOBA", label: "Córdoba" },
	{ value: "CUNDINAMARCA", label: "Cundinamarca" },
	{ value: "GUAINIA", label: "Guainía" },
	{ value: "GUAVIARE", label: "Guaviare" },
	{ value: "HUILA", label: "Huila" },
	{ value: "LA GUAJIRA", label: "La Guajira" },
	{ value: "MAGDALENA", label: "Magdalena" },
	{ value: "META", label: "Meta" },
	{ value: "NARIÑO", label: "Nariño" },
	{ value: "NORTE DE SANTANDER", label: "Norte de Santander" },
	{ value: "PUTUMAYO", label: "Putumayo" },
	{ value: "QUINDIO", label: "Quindío" },
	{ value: "RISARALDA", label: "Risaralda" },
	{ value: "SANTAFE DE BOGOTA D.C", label: "Bogotá D.C." },
	{ value: "SANTANDER", label: "Santander" },
	{ value: "SUCRE", label: "Sucre" },
	{ value: "TOLIMA", label: "Tolima" },
	{ value: "VALLE DEL CAUCA", label: "Valle del Cauca" },
	{ value: "VAUPES", label: "Vaupés" },
	{ value: "VICHADA", label: "Vichada" },
] as const;

export const DEPARTMENT_NAMES: Record<string, string> = Object.fromEntries(
	DEPARTMENTS.map((d) => [d.value, d.label]),
);
